apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
    # DEMO ONLY: change me-basicauth-username and me-basicauth-password for non-local environments
    me-basicauth-username: YWRtaW4=
    me-basicauth-password: cGFzcw==
